FROM python:latest
MAINTAINER Kazuki_Kamizuru<kamizuru@k2ss.info>

RUN pip install \
    mysqlclient \
    requests \
    python-dotenv \
    django \
    djangorestframework \
    django-debug-toolbar

CMD ["/app/manage.py", "runserver", "0.0.0.0:8000"]
