branches:
  only:
  - master

language: python

sudo: false

cache:
  directories:
    - $HOME/.yarn-cache

python:
  - 3.4
  - 3.5
  - 3.6

services:
  - postgresql

before_install:
  - nvm install --lts
  - nvm alias default lts/*
  - node --version
  - npm i -g yarn

install:
  - pip install pipenv
  - pipenv install --dev
  - yarn

before_script:
  - cp .env.example .env
  - echo "SECRET_KEY='$(pipenv run kg)'" >> .env

script:
  - pipenv run python manage.py test --noinput
  - yarn run tslint
  - yarn run sasslint

notifications:
  email: false
