branches:
  only:
  - master

language: python

sudo: false

cache:
  directories:
    - node_modules

python:
  - 3.4
  - 3.5
  - 3.6

services:
  - mysql

before_install:
  - nvm install node
  - nvm alias default node
  - node --version

install:
  - pip install pipenv
  - pipenv install --dev
  - npm install

before_script:
  - cp .env.example .env

script:
  - pipenv run python manage.py test --noinput
  - npm run tslint
  - npm run sasslint

notifications:
  email: false
