version: '3'
services:
  backend:
    build: ./docker/api
    command: sh -c 'pipenv install -d && pipenv run python manage.py runserver 0.0.0.0:8000'
    working_dir: /src
    volumes:
      - ./:/src
    ports:
      - '8000:8000'
    depends_on:
      - database
  frontend:
    image: node:10
    working_dir: /src
    volumes:
      - ./:/src
    command: sh -c 'yarn && yarn dev'
  database:
    image: postgres:10.4
    ports:
      - 15432:5432
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: myrecipe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
