version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c 'pipenv install -d && pipenv run pm runserver 0.0.0.0:8000'
    working_dir: /src
    volumes:
      - ./:/src
    ports:
      - 8000:8000
    depends_on:
      - database
  frontend:
    image: node:14.16
    working_dir: /src
    volumes:
      - ./:/src
      - node_modules:/src/node_modules
    command: sh -c 'yarn && yarn dev'
  database:
    image: postgres:10.4
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: myrecipe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  node_modules: null
