version: '3'
services:
  postgres:
    image: postgres:10.4
    ports:
      - 15432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: myrecipe
      POSTGRES_USER: postgres
