# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 23:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('created_by', models.CharField(max_length=10)),
                ('modified_by', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=5)),
                ('ingestion_kcal', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('create_number_of_times', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
            ],
            options={
                'db_table': 'cuisine',
            },
        ),
        migrations.CreateModel(
            name='Foodstuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('created_by', models.CharField(max_length=10)),
                ('modified_by', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=100)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodstuffs', to='core.Cuisine')),
            ],
            options={
                'db_table': 'foodstuffs',
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('created_by', models.CharField(max_length=10)),
                ('modified_by', models.CharField(max_length=10)),
                ('sort_order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='並び順')),
                ('description', models.CharField(max_length=255, verbose_name='手順')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='core.Cuisine')),
            ],
            options={
                'db_table': 'cooking_instructions',
            },
        ),
    ]
