# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 19:32
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                # ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ログインユーザ',
                'verbose_name_plural': 'ログインユーザ',
                'managed': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='cuisine',
            options={'verbose_name': 'メニュー', 'verbose_name_plural': 'メニュー'},
        ),
        migrations.AlterModelOptions(
            name='foodstuff',
            options={'verbose_name': '食材', 'verbose_name_plural': '食材'},
        ),
        migrations.AlterModelOptions(
            name='instruction',
            options={'verbose_name': '調理手順', 'verbose_name_plural': '調理手順'},
        ),
    ]
