# Generated by Django 2.0.5 on 2018-06-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='classification',
            field=models.CharField(max_length=5),
        ),
    ]
