# Generated by Django 2.0.5 on 2018-06-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180625_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザ', 'verbose_name_plural': 'ユーザ'},
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='classification',
            field=models.CharField(max_length=20),
        ),
    ]
