# Generated by Django 2.0.5 on 2018-07-10 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180625_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='create_number_of_times',
        ),
        migrations.AddField(
            model_name='cuisine',
            name='serves',
            field=models.IntegerField(blank=True, null=True, validators=[
                                      django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
