# Generated by Django 2.0.9 on 2019-01-02 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190101_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('token', models.CharField(max_length=128)),
                ('expired', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザトークン',
                'verbose_name_plural': 'ユーザトークン',
                'db_table': 'user_tokens',
                'abstract': False,
            },
        ),
    ]
