name: Myrecipe Dispatch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Base branch'
        required: true
        default: master
      tag_name:
        description: 'Create tag'
        required: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        git tag ${{ github.event.inputs.tag_name }} origin/${{ github.event.inputs.branch_name }}
        git tag
