name: Create Tag

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Base branch'
        required: true
        default: main
      tag_name:
        description: 'Create tag'
        required: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create tag
        run: |
          git tag ${{ github.event.inputs.tag_name }} origin/${{ github.event.inputs.branch_name }}
          git push origin ${{ github.event.inputs.tag_name }}
